### Different ways to test multiple flags

In [4]:
x, y, z = 0, 1, 0

In [5]:
if x == 1 or y == 1 or z == 1:
    print('passed')

passed


In [6]:
if 1 in (x, y, z):
    print('passed')

passed


In [7]:
#test for truthliness
if x or y or z:
    print('passed')

passed


In [8]:
#another test for truthliness
if any((x, y, z)):
    print('passed')

passed


In [9]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


### Sort dictionary by value

In [10]:
xs = {'a':4, 'b': 3, 'c': 2, 'd': 1}

In [11]:
sorted(xs.items(), key = lambda x: x[1])

[('d', 1), ('c', 2), ('b', 3), ('a', 4)]

In [12]:
import operator
sorted(xs.items(), key = operator.itemgetter(1))

[('d', 1), ('c', 2), ('b', 3), ('a', 4)]

### "is" vs "=="

In [13]:
a = [1, 2, 3]
b = a

In [14]:
a is b

True

In [15]:
a == b

True

In [16]:
c = list(a)

In [17]:
a == c

True

In [18]:
a is c

False

In [19]:
# • "is" expressions evaluate to True if two 
#   variables point to the same object

# • "==" evaluates to True if the objects 
#   referred to by the variables are equal

### Execution time of small bits of code

In [20]:
import timeit

In [21]:
timeit.timeit('"-".join(str(n) for n in range(100))', number = 10000)

0.7135268101135253

In [22]:
timeit.timeit('"-".join([str(n) for n in range(100)])', number = 10000)

0.3351749578973747

In [23]:
timeit.timeit('"-".join(map(str, range(100)))', number = 10000)

0.2341923779921944

### Function argument unpacking

In [24]:
def myfunc(x, y, z):
    print(x, y, z)

In [25]:
tuple_vec = (1, 0, 1)
dict_vec = {'x': 1, 'y': 0, 'z': 1}

In [26]:
myfunc(*tuple_vec)

1 0 1


In [27]:
myfunc(**dict_vec)

1 0 1


In [28]:
myfunc(*dict_vec)

x y z


### The get() method on Python dicts and its "default" arg

In [29]:
name_for_userid = {382: 'Alice', 590: 'Bob', 951: 'Dilbert'}

In [30]:
def greeting(userid):
    return "Hi %s!" % name_for_userid.get(userid, "there")

In [31]:
greeting(382)

'Hi Alice!'

In [32]:
greeting(33333)

'Hi there!'

### Merge two dictionaries

In [33]:
x = {'a': 1, 'b': 2}
y = {'b': 3, 'c': 4}

In [34]:
z = {**x, **y}
z

{'a': 1, 'b': 3, 'c': 4}

In [35]:
z = {**y, **x}
z

{'a': 1, 'b': 2, 'c': 4}

In [36]:
z = dict(x, **y)
z

{'a': 1, 'b': 3, 'c': 4}

In [37]:
z = dict(y, **x)
z

{'a': 1, 'b': 2, 'c': 4}

### Small anonymous functions using lambda

In [38]:
add = lambda x, y: x+y

In [39]:
add(5, 3)

8

In [40]:
def add(x, y):
    return x + y

In [41]:
add(5, 3)

8

In [42]:
(lambda x, y: x +y)(5, 3)

8

### Functions are first-class citizens in Python

In [43]:
def myfunc(a, b):
    return a + b

In [44]:
funcs = [myfunc]
funcs[0]

<function __main__.myfunc>

In [45]:
funcs[0](2, 3)

5

### Pretty-print Python dicts

In [46]:
my_mapping = {'a': 23, 'b': 42, 'c': 0xc0ffee}
my_mapping

{'a': 23, 'b': 42, 'c': 12648430}

In [47]:
import json

In [48]:
print(json.dumps(my_mapping, indent = 4, sort_keys = True))

{
    "a": 23,
    "b": 42,
    "c": 12648430
}


In [49]:
# Note this only works with dicts containing
# primitive types (check out the "pprint" module):
json.dumps({all: 'yup'})

TypeError: keys must be a string

### Python's namedtuples

In [ ]:
from collections import namedtuple

In [ ]:
Car = namedtuple('Car', 'color mileage')

In [ ]:
my_car = Car('red', 3812.4)
my_car.color

In [ ]:
my_car.mileage

In [ ]:
my_car

In [ ]:
# Like tuples, namedtuples are immutable:
my_car.color = 'blue'

### Crazy dictionary expression

In [ ]:
{True: 'yes', 1: 'no', 1.0: 'maybe'}

In [ ]:
True is 1

In [ ]:
True == 1

### Max split

In [ ]:
string = "a_b_c"
print(string.split("_", 1))

In [ ]:
s = "foo    bar   foobar foo"
print(s.split(None, 2))

### Dicts can be used to emulate switch/case statements

In [ ]:
def dispatch_if(operator, x, y):
    if operator == 'add':
        return x + y
    elif operator == 'sub':
        return x - y
    elif operator == 'mul':
        return x * y
    elif operator == 'div':
        return x / y
    else:
        return None

In [ ]:
def dispatch_dict(operator, x, y):
    return {
        'add': lambda: x + y,
        'sub': lambda: x - y,
        'mul': lambda: x * y,
        'div': lambda: x / y,
    }.get(operator, lambda: None)()

In [ ]:
print(dispatch_if('add', 2 , 8))

In [ ]:
print(dispatch_dict('add', 2, 8))

In [ ]:
print(dispatch_if('unknown', 2, 8))

In [ ]:
print(dispatch_dict('unknown', 2, 8))

### Python's built-in HTTP server

In [ ]:
python3 -m http.server

### str() and repr()

In [ ]:
a = [1, 2, 3, 4]
b = 'sample string'

In [ ]:
str(a)

In [ ]:
repr(a)

In [ ]:
str(b)

In [ ]:
repr(b)

In [ ]:
# The goal of repr() is to be unambiguous
# The goal of str() is to be readable

### Inspecting Python Modules and Classes With "dir()" And "help()"

In [ ]:
import requests

In [ ]:
dir(requests)

In [ ]:
help(requests)

### Python's list comprehensions

In [ ]:
even_squares = [x * x for x in range(10) if not x%2]

In [ ]:
even_squares

### Type Hints

In [ ]:
def add_this(a: int, b: int) -> int:
    return a + b

In [ ]:
add_this(4, 5)

In [ ]:
# does not guarantee returning int:
add_this('d', 'b')

In [ ]:
# you can use mypy to debug .py file to find inconsistencies in Type Hints

### Python and MathPlotLib

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
np.random.seed(444)

In [ ]:
fig, _ = plt.subplots()
type(fig)

In [ ]:
one_tick = fig.axes[0].yaxis.get_major_ticks()[0]
type(one_tick)

In [ ]:
x = np.arange(0, 5, 0.1)
y = np.sin(x)
plt.plot(x, y)

In [ ]:
plt.show()

### Python list slicing

In [ ]:
# clearing all the elements from list
lst = [1, 2, 3, 4, 5]
del lst[:]
lst

In [ ]:
# You can replace all elements of a list
# without creating a new list object:
a = lst
lst[:] = [7, 8, 9]
lst

In [ ]:
a

In [ ]:
a is lst

In [ ]:
# You can also create a (shallow) copy of a list:
b = lst[:]
b

In [ ]:
b is lst

### import antigravity

In [ ]:
import antigravity

### Finding the most common elements in an iterable

In [ ]:
import collections

In [ ]:
c = collections.Counter('helloworld')
c

In [ ]:
c.most_common(3)

### Reversing the string

In [ ]:
### “[::-1]” Slicing Trick:
def reverse_string1(s):
    return s[::-1]

reverse_string1('TURBO')

In [ ]:
### Using  reversed() and str.join():
def reverse_string2(s):
    return ''.join(reversed(s))

reverse_string2('TURBO')

In [ ]:
### In-Place String Reversal Algorithm:
def reverse_string3(s):
    chars = list(s)
    for i in range(len(s) // 2):
        tmp = chars[i]
        chars[i] = chars[len(s) - i - 1]
        chars[len(s) - i - 1] = tmp
    return ''.join(chars)

reverse_string3('TURBO')

In [ ]:
###Performance Comparison
import timeit
s = 'abcdefghijklmnopqrstuvwxyz' * 10

In [ ]:
timeit.repeat(lambda: reverse_string1(s))

In [ ]:
timeit.repeat(lambda: reverse_string2(s))

In [ ]:
timeit.repeat(lambda: reverse_string3(s))

### itertools.permutations() generates permutations

In [ ]:
import itertools
for p in itertools.permutations('ABCD'):
     print(p)

### Using `__repr__`  vs `__str__`

In [53]:
import datetime
today = datetime.date.today()

In [54]:
# Result of __str__ should be readable:
str(today)

'2018-04-08'

In [55]:
# Result of __repr__ should be unambiguous:
repr(today)

'datetime.date(2018, 4, 8)'

In [56]:
today

datetime.date(2018, 4, 8)

### Learn what operations can be performed on an element

In [51]:
my_string = 'I am a string'
dir(my_string)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',
 'zfill']

In [57]:
dir(today)

['__add__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__ne__',
 '__new__',
 '__radd__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rsub__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 'ctime',
 'day',
 'fromordinal',
 'fromtimestamp',
 'isocalendar',
 'isoformat',
 'isoweekday',
 'max',
 'min',
 'month',
 'replace',
 'resolution',
 'strftime',
 'timetuple',
 'today',
 'toordinal',
 'weekday',
 'year']

### Disassembling functions with dis()

In [1]:
# You can use Python's built-in "dis"
# module to disassemble functions and
# inspect their CPython VM bytecode:

def greet(name):
    return 'Hello, ' + name + '!'

In [2]:
greet('Kate')

'Hello, Kate!'

In [3]:
import dis
dis.dis(greet)

  2           0 LOAD_CONST               1 ('Hello, ')
              2 LOAD_FAST                0 (name)
              4 BINARY_ADD
              6 LOAD_CONST               2 ('!')
              8 BINARY_ADD
             10 RETURN_VALUE


### @classmethod vs @staticmethod vs "plain" methods

In [1]:
class MyClass:
    def method(self):
        """
        Instance methods need a class instance and
        can access the instance through `self`.
        """
        return 'instance method called', self

    @classmethod
    def classmethod(cls):
        """
        Class methods don't need a class instance.
        They can't access the instance (self) but
        they have access to the class itself via `cls`.
        """
        return 'class method called', cls

    @staticmethod
    def staticmethod():
        """
        Static methods don't have access to `cls` or `self`.
        They work like regular functions but belong to
        the class's namespace.
        """
        return 'static method called'

In [2]:
obj = MyClass()
obj.method()

('instance method called', <__main__.MyClass at 0x2a663bfc048>)

In [3]:
obj.classmethod()

('class method called', __main__.MyClass)

In [4]:
obj.staticmethod()

'static method called'

In [5]:
# Calling instance methods fails
# if we only have the class object:
MyClass.classmethod()

('class method called', __main__.MyClass)

In [6]:
MyClass.staticmethod()

'static method called'

In [7]:
MyClass.method()

TypeError: method() missing 1 required positional argument: 'self'

### Numpy arrays

In [1]:
import numpy as np
arr = np.arange(36).reshape(3, 4, 3)
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [4]:
arr = np.arange(81).reshape(3, 3, 9)
arr

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23, 24, 25, 26]],

       [[27, 28, 29, 30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49, 50, 51, 52, 53]],

       [[54, 55, 56, 57, 58, 59, 60, 61, 62],
        [63, 64, 65, 66, 67, 68, 69, 70, 71],
        [72, 73, 74, 75, 76, 77, 78, 79, 80]]])

In [7]:
np.random.seed(444)
x = np.random.choice([False, True], size=10)
x

array([ True, False,  True, False,  True, False,  True, False, False,  True], dtype=bool)

In [8]:
def count_transitions(x) -> int:
     count = 0
     for i, j in zip(x[:-1], x[1:]):
         if j and not i:
             count += 1
     return count

count_transitions(x)

4

In [9]:
np.count_nonzero(x[:-1] < x[1:])

4

### IP addresses in Python 3

In [1]:
import ipaddress

In [2]:
ipaddress.ip_address('192.168.1.2')

IPv4Address('192.168.1.2')

In [3]:
ipaddress.ip_address('2001:af3::')

IPv6Address('2001:af3::')

### Lambda functions

In [6]:
add = lambda x, y: x + y
add(5, 3)

8

In [7]:
def add(x, y):
   return x + y
add(5, 3)

8

In [8]:
(lambda x, y: x + y)(5, 3)

8

### Python 3 Allows Unicode Variable Names

In [2]:
class Spin̈alTap: pass

In [3]:
Spin̈alTap()

<__main__.Spin̈alTap at 0x22586e85320>

### "for" (and "while") loops can have an "else" branch?!

In [1]:
def contains(haystack, needle):
    """
    Throw a ValueError if `needle` not
    in `haystack`.
    """
    for item in haystack:
        if item == needle:
            break
    else:
        # The `else` here is a
        # "completion clause" that runs
        # only if the loop ran to completion
        # without hitting a `break` statement.
        raise ValueError('Needle not found')

In [4]:
print(contains([23, 'needle', 0xbadc0ffee], 'needle'))

None


In [5]:
print(contains([23, 42, 0xbadc0ffee], 'needle'))

ValueError: Needle not found

In [6]:
def better_contains(haystack, needle):
    for item in haystack:
        if item == needle:
            return
    raise ValueError('Needle not found')

In [8]:
# Note: Typically you'd write something
# like this to do a membership test,
# which is much more Pythonic:
if needle not in haystack:
    raise ValueError('Needle not found')

NameError: name 'needle' is not defined